CREATE TABLE users (
    id      INT AUTO_INCREMENT, PRIMARY KEY(id),
    email   VARCHAR(255),
    pass    VARCHAR(32),
    sum     INT,
    created DATETIME,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;